bazinga_exposetranslation_js:
    pattern:  /translations/{domain}.{_format}
    defaults: { _controller: bazinga.exposetranslation.controller:getTranslationsAction, domain: "messages", _format: "js" }
    methods:  [ GET ]
    options:
        i18n: false
    requirements:
        _format: js|json
        domain: "[\w]+"
